const table=document.body.dataset.table;
const configurations={
  programmes:{fields:[['name','Name','text',true],['slug','Slug','text',true],['summary','Summary','textarea'],['description','Description','textarea'],['eligibility','Eligibility','textarea'],['status','Status','select',['draft','published','paused','archived']]]},
  posts:{fields:[['title','Title','text',true],['slug','Slug','text',true],['excerpt','Excerpt','textarea'],['body','Article body','textarea'],['category','Category','text'],['content_type','Content type','select',['article','guide','resource','video','download','news']],['status','Status','select',['draft','in_review','published','archived']]]},
  gallery_items:{fields:[['title','Title','text',true],['image_url','Image URL','url',true],['caption','Caption','textarea'],['category','Category','text'],['sort_order','Order','number'],['consent_confirmed','Consent confirmed','checkbox'],['status','Status','select',['draft','published','archived']]]}
};
const config=configurations[table],form=document.querySelector('#record-form'),list=document.querySelector('#record-list'),statusNode=document.querySelector('#status');
let records=[];
form.innerHTML='<input type="hidden" name="id">'+config.fields.map(([name,label,type,options])=>{if(type==='textarea')return `<label class="field">${label}<textarea name="${name}"></textarea></label>`;if(type==='select')return `<label class="field">${label}<select name="${name}">${options.map(v=>`<option value="${v}">${v}</option>`).join('')}</select></label>`;if(type==='checkbox')return `<label class="field"><span><input name="${name}" type="checkbox"> ${label}</span></label>`;return `<label class="field">${label}<input name="${name}" type="${type}" ${options===true?'required':''}></label>`}).join('')+'<button class="button" type="submit">Save record</button> <button class="button" type="button" id="clear">New record</button>';
async function request(method,body){const response=await fetch(`/api/content?table=${table}`,{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed.');return data;}
async function load(){records=await request('GET');list.innerHTML=records.map((record,index)=>`<article class="card"><h2>${escapeText(record.name||record.title)}</h2><p>${escapeText(record.summary||record.excerpt||record.caption||'')}</p><p><strong>${escapeText(record.status)}</strong></p><button class="button edit" data-index="${index}">Edit</button> <button class="button remove" data-id="${record.id}">Delete</button></article>`).join('')||'<p>No records yet. Use the form to create one.</p>';list.querySelectorAll('.edit').forEach(button=>button.onclick=()=>fill(records[Number(button.dataset.index)]));list.querySelectorAll('.remove').forEach(button=>button.onclick=async()=>{if(!confirm('Delete this record?'))return;await request('DELETE',{id:button.dataset.id});await load()});}
function fill(record={}){config.fields.forEach(([name])=>{const field=form.elements[name];if(field.type==='checkbox')field.checked=Boolean(record[name]);else field.value=record[name]??''});form.elements.id.value=record.id||'';window.scrollTo({top:0,behavior:'smooth'});}
form.onsubmit=async event=>{event.preventDefault();const values={};config.fields.forEach(([name,,type])=>{const field=form.elements[name];values[name]=type==='checkbox'?field.checked:type==='number'&&field.value!==''?Number(field.value):field.value||null});const id=form.elements.id.value;statusNode.hidden=false;statusNode.textContent='Saving…';try{await request(id?'PATCH':'POST',id?{id,...values}:values);fill();statusNode.textContent='Saved.';await load()}catch(error){statusNode.textContent=error.message}};
form.querySelector('#clear').onclick=()=>fill();
function escapeText(value){const node=document.createElement('div');node.textContent=String(value||'');return node.innerHTML;}
load().catch(error=>{list.textContent=error.message});
