const table=document.body.dataset.table;
const configurations={
  programmes:{fields:[['name','Name','text',true],['slug','Slug','text',true],['summary','Summary','textarea'],['description','Description','textarea'],['eligibility','Eligibility','textarea'],['status','Status','select',['draft','published','paused','archived']]]},
  posts:{fields:[['title','Title','text',true],['slug','Slug','text',true],['excerpt','Excerpt','textarea'],['body','Article body','textarea'],['category','Category','text'],['content_type','Content type','select',['article','guide','resource','video','download','news']],['status','Status','select',['draft','in_review','published','archived']]]},
  gallery_items:{fields:[['title','Title','text',true],['image_url','Image URL','url',true],['caption','Caption','textarea'],['category','Category','text'],['sort_order','Order','number'],['consent_confirmed','Consent confirmed','checkbox'],['status','Status','select',['draft','published','archived']] ]}
};
const config=configurations[table],form=document.querySelector('#record-form'),list=document.querySelector('#record-list'),statusNode=document.querySelector('#status');
let records=[];
function fieldMarkup([name,label,type,options]){
  if(type==='textarea')return `<label class="field">${label}<textarea name="${name}"></textarea></label>`;
  if(type==='select')return `<label class="field">${label}<select name="${name}">${options.map(v=>`<option value="${v}">${v}</option>`).join('')}</select></label>`;
  if(type==='checkbox')return `<label class="field"><span><input name="${name}" type="checkbox"> ${label}</span></label>`;
  return `<label class="field">${label}<input name="${name}" type="${type}" ${options===true?'required':''}></label>`;
}
const imageUpload=table==='gallery_items'?'<fieldset class="upload-panel"><legend>Upload a photo</legend><p>Choose a JPG, PNG, WebP or AVIF image up to 10 MB. For safety, do not upload a survivor-identifying image unless you have documented permission to publish it.</p><label class="field">Photo file<input id="gallery-file" type="file" accept="image/jpeg,image/png,image/webp,image/avif"></label><button class="button" id="upload-image" type="button">Upload photo</button><p id="upload-status" role="status" aria-live="polite"></p><img id="image-preview" alt="Selected gallery photo preview" hidden style="max-width:100%;max-height:320px;border-radius:12px"></fieldset>':'';
form.innerHTML='<input type="hidden" name="id">'+imageUpload+config.fields.map(fieldMarkup).join('')+'<button class="button" type="submit">Save record</button> <button class="button" type="button" id="clear">New record</button>';
async function request(method,body){const response=await fetch(`/api/content?table=${table}`,{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed.');return data;}
async function load(){records=await request('GET');list.innerHTML=records.map((record,index)=>`<article class="card"><h2>${escapeText(record.name||record.title)}</h2><p>${escapeText(record.summary||record.excerpt||record.caption||'')}</p><p><strong>${escapeText(record.status)}</strong></p>${table==='gallery_items'&&record.image_url?`<img src="${escapeAttribute(record.image_url)}" alt="${escapeAttribute(record.title)}" loading="lazy" style="max-width:220px;border-radius:10px">`:''}<p><button class="button edit" data-index="${index}">Edit</button> <button class="button remove" data-id="${escapeAttribute(record.id)}">Delete</button></p></article>`).join('')||'<p>No records yet. Use the form to create one.</p>';list.querySelectorAll('.edit').forEach(button=>button.onclick=()=>fill(records[Number(button.dataset.index)]));list.querySelectorAll('.remove').forEach(button=>button.onclick=async()=>{if(!confirm('Delete this record?'))return;try{await request('DELETE',{id:button.dataset.id});await load()}catch(error){showStatus(error.message)}});}
function fill(record={}){config.fields.forEach(([name])=>{const field=form.elements[name];if(field.type==='checkbox')field.checked=Boolean(record[name]);else field.value=record[name]??''});form.elements.id.value=record.id||'';if(table==='gallery_items'){document.querySelector('#gallery-file').value='';document.querySelector('#image-preview').hidden=!record.image_url;if(record.image_url)document.querySelector('#image-preview').src=record.image_url;}window.scrollTo({top:0,behavior:'smooth'});}
function showStatus(message){statusNode.hidden=false;statusNode.textContent=message;}
if(table==='gallery_items'){
  const file=document.querySelector('#gallery-file'),preview=document.querySelector('#image-preview'),uploadStatus=document.querySelector('#upload-status');
  file.addEventListener('change',()=>{const image=file.files[0];preview.hidden=!image;if(image){preview.src=URL.createObjectURL(image);uploadStatus.textContent='Preview only — select Upload photo to store it.';}});
  document.querySelector('#upload-image').onclick=async()=>{const image=file.files[0];if(!image){uploadStatus.textContent='Choose a photo first.';return;}if(image.size>10*1024*1024){uploadStatus.textContent='This photo is over 10 MB. Choose a smaller image.';return;}uploadStatus.textContent='Uploading securely…';const data=new FormData();data.append('image',image);try{const response=await fetch('/api/gallery-upload',{method:'POST',credentials:'same-origin',body:data}),result=await response.json();if(!response.ok)throw Error(result.error||'Upload failed.');form.elements.image_url.value=result.image_url;uploadStatus.textContent='Photo uploaded. Add a title and save the gallery record.';preview.src=result.image_url;preview.hidden=false;}catch(error){uploadStatus.textContent=error.message;}};
}
form.onsubmit=async event=>{event.preventDefault();const values={};config.fields.forEach(([name,,type])=>{const field=form.elements[name];values[name]=type==='checkbox'?field.checked:type==='number'&&field.value!==''?Number(field.value):field.value||null});const id=form.elements.id.value;showStatus('Saving…');try{await request(id?'PATCH':'POST',id?{id,...values}:values);fill();showStatus('Saved.');await load()}catch(error){showStatus(error.message)}};
form.querySelector('#clear').onclick=()=>fill();
function escapeText(value){const node=document.createElement('div');node.textContent=String(value||'');return node.innerHTML;}
function escapeAttribute(value){return escapeText(value).replace(/"/g,'&quot;');}
load().catch(error=>{list.textContent=error.message});
