const table=document.body.dataset.table;
const configurations={
  programmes:{fields:[['name','Name','text',true],['slug','Slug','text',true],['summary','Summary','textarea'],['description','Description','textarea'],['eligibility','Eligibility','textarea'],['status','Status','select',['draft','published','paused','archived']]]},
  posts:{fields:[['title','Title','text',true],['slug','Slug','text',true],['excerpt','Excerpt','textarea'],['body','Article body','textarea'],['category','Category','text'],['content_type','Content type','select',['article','guide','resource','video','download','news']],['status','Status','select',['draft','in_review','published','archived']]]},
  gallery_items:{fields:[['title','Title','text',true],['image_url','Image URL','url',true],['caption','Caption','textarea'],['category','Category','text'],['sort_order','Order','number'],['consent_confirmed','Consent confirmed','checkbox'],['status','Status','select',['draft','published','archived']]]}
};
const config=configurations[table],form=document.querySelector('#record-form'),list=document.querySelector('#record-list'),statusNode=document.querySelector('#status');
let records=[];
function fieldMarkup([name,label,type,options]){
  if(type==='textarea')return `<label class="field">${label}<textarea name="${name}"></textarea></label>`;
  if(type==='select')return `<label class="field">${label}<select name="${name}">${options.map(v=>`<option value="${v}">${v}</option>`).join('')}</select></label>`;
  if(type==='checkbox')return `<label class="field"><span><input name="${name}" type="checkbox"> ${label}</span></label>`;
  return `<label class="field">${label}<input name="${name}" type="${type}" ${options===true?'required':''}></label>`;
}
const imageUpload=table==='gallery_items'?'<fieldset class="upload-panel"><legend>Upload multiple photos</legend><p>Select several JPG, PNG, WebP or AVIF images, up to 10 MB each. Files go into the public gallery bucket, but every new record is saved as a draft. Publish only images you have documented permission to share publicly.</p><label class="field">Choose photos<input id="gallery-files" type="file" accept="image/jpeg,image/png,image/webp,image/avif" multiple></label><label class="field">Caption for all selected photos<textarea id="batch-caption" maxlength="1000" placeholder="Optional shared caption"></textarea></label><button class="button" id="upload-images" type="button">Upload selected photos</button><p id="upload-status" role="status" aria-live="polite"></p><div id="upload-previews" class="gallery-grid"></div></fieldset>':'';
form.innerHTML='<input type="hidden" name="id">'+imageUpload+config.fields.map(fieldMarkup).join('')+'<button class="button" type="submit">Save record</button> <button class="button" type="button" id="clear">New record</button>';
async function request(method,body){const response=await fetch(`/api/content?table=${table}`,{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed.');return data;}
async function load(){records=await request('GET');list.innerHTML=records.map((record,index)=>`<article class="card"><h2>${escapeText(record.name||record.title)}</h2><p>${escapeText(record.summary||record.excerpt||record.caption||'')}</p><p><strong>${escapeText(record.status)}</strong></p>${table==='gallery_items'&&record.image_url?`<img src="${escapeAttribute(record.image_url)}" alt="${escapeAttribute(record.title)}" loading="lazy" style="max-width:220px;border-radius:10px">`:''}<p><button class="button edit" data-index="${index}">Edit</button> <button class="button remove" data-id="${escapeAttribute(record.id)}">Delete</button></p></article>`).join('')||'<p>No records yet. Use the form to create one.</p>';list.querySelectorAll('.edit').forEach(button=>button.onclick=()=>fill(records[Number(button.dataset.index)]));list.querySelectorAll('.remove').forEach(button=>button.onclick=async()=>{if(!confirm('Delete this record?'))return;try{await request('DELETE',{id:button.dataset.id});await load()}catch(error){showStatus(error.message)}});}
function fill(record={}){config.fields.forEach(([name])=>{const field=form.elements[name];if(field.type==='checkbox')field.checked=Boolean(record[name]);else field.value=record[name]??''});form.elements.id.value=record.id||'';if(table==='gallery_items')document.querySelector('#gallery-files').value='';window.scrollTo({top:0,behavior:'smooth'});}
function showStatus(message){statusNode.hidden=false;statusNode.textContent=message;}
if(table==='gallery_items'){
  const files=document.querySelector('#gallery-files'),previewList=document.querySelector('#upload-previews'),uploadStatus=document.querySelector('#upload-status'),uploadButton=document.querySelector('#upload-images');
  files.addEventListener('change',()=>{previewList.replaceChildren();for(const file of [...files.files]){const card=document.createElement('article');card.className='gallery-card';const image=document.createElement('img');image.src=URL.createObjectURL(file);image.alt=`Preview of ${file.name}`;image.loading='lazy';const caption=document.createElement('p');caption.textContent=`${file.name} · ${(file.size/1024/1024).toFixed(1)} MB`;card.append(image,caption);previewList.append(card);}uploadStatus.textContent=files.files.length?`${files.files.length} photo(s) selected.`:'No photos selected.';});
  uploadButton.onclick=async()=>{const selected=[...files.files];if(!selected.length){uploadStatus.textContent='Choose one or more photos first.';return;}if(selected.length>20){uploadStatus.textContent='Upload up to 20 photos at a time.';return;}const invalid=selected.find(file=>file.size>10*1024*1024);if(invalid){uploadStatus.textContent=`${invalid.name} is over the 10 MB limit. Choose smaller photos.`;return;}uploadButton.disabled=true;let succeeded=0;const failures=[];for(let i=0;i<selected.length;i++){const file=selected[i];uploadStatus.textContent=`Uploading photo ${i+1} of ${selected.length}: ${file.name}`;try{const body=new FormData();body.append('image',file);const response=await fetch('/api/gallery-upload',{method:'POST',credentials:'same-origin',body}),result=await response.json();if(!response.ok)throw Error(result.error||'Upload failed.');const title=file.name.replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ').trim()||'Gallery photo';await request('POST',{title,image_url:result.image_url,caption:document.querySelector('#batch-caption').value.trim()||null,category:null,sort_order:records.length+succeeded,consent_confirmed:false,status:'draft'});succeeded++;}catch(error){failures.push(`${file.name}: ${error.message}`);}}
    uploadButton.disabled=false;await load().catch(()=>{});files.value='';previewList.replaceChildren();uploadStatus.textContent=`Uploaded ${succeeded} of ${selected.length} photos as drafts.${failures.length?` ${failures.join(' | ')}`:' Review each draft, record consent, then publish when ready.'}`;
  };
}
form.onsubmit=async event=>{event.preventDefault();const values={};config.fields.forEach(([name,,type])=>{const field=form.elements[name];values[name]=type==='checkbox'?field.checked:type==='number'&&field.value!==''?Number(field.value):field.value||null});const id=form.elements.id.value;showStatus('Saving…');try{await request(id?'PATCH':'POST',id?{id,...values}:values);fill();showStatus('Saved.');await load()}catch(error){showStatus(error.message)}};
form.querySelector('#clear').onclick=()=>fill();
function escapeText(value){const node=document.createElement('div');node.textContent=String(value||'');return node.innerHTML;}
function escapeAttribute(value){return escapeText(value).replace(/"/g,'&quot;');}
load().catch(error=>{list.textContent=error.message});
